--Table creation

CREATE TABLE CUSTOMERS (
	CUSTID INTEGER NOT NULL,
	FIRST_NAME CHARACTER VARYING(8) NOT NULL,
	LAST_NAME CHARACTER VARYING(7) NOT NULL,
	EMAIL CHARACTER VARYING(19) NOT NULL,
	PHONE BIGINT NOT NULL,
	ADDRESS CHARACTER VARYING(11) NOT NULL,
	CITY CHARACTER VARYING(5) NOT NULL,
	STATE CHARACTER VARYING(6) NOT NULL,
	POSTAL_CODE INTEGER NOT NULL
)
SELECT
	*
FROM
	CUSTOMERS

CREATE TABLE PIZZA_TYPES (
	PIZZA_TYPE_ID CHARACTER VARYING(50) NOT NULL,
	NAME CHARACTER VARYING(100) NOT NULL,
	CATEGORY CHARACTER VARYING(50) NOT NULL,
	INGREDIENTS TEXT NOT NULL
)
SELECT
	*
FROM
	PIZZA_TYPES

CREATE TABLE PIZZAS (
	PIZZA_ID CHARACTER VARYING(14) NOT NULL,
	PIZZA_TYPE_ID CHARACTER VARYING(12) NOT NULL,
	SIZE CHARACTER VARYING(3) NOT NULL,
	PRICE NUMERIC(5, 2) NOT NULL
)
SELECT
	*
FROM
	PIZZAS

CREATE TABLE ORDERS (
	ORDER_ID INTEGER NOT NULL,
	ORDER_DATE DATE NOT NULL,
	ORDER_TIME CHARACTER VARYING(8) NOT NULL,
	CUSTID INTEGER NOT NULL,
	STATUS CHARACTER VARYING(9) NOT NULL
)
SELECT
	*
FROM
	ORDERS

CREATE TABLE ORDER_DETAILS (
	ORDER_DETAILS_ID INTEGER NOT NULL,
	ORDER_ID INTEGER NOT NULL,
	PIZZA_ID CHARACTER VARYING(14) NOT NULL,
	QUANTITY INTEGER NOT NULL
)
SELECT
	*
FROM
	ORDER_DETAILS;


--Adding the constratints

ALTER TABLE CUSTOMERS
ADD CONSTRAINT CUSTOMERS_PKEY PRIMARY KEY (CUSTID);

ALTER TABLE PIZZAS
ADD CONSTRAINT PIZZAS_PKEY PRIMARY KEY (PIZZA_ID);

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT ORDER_DETAILS_PKEY PRIMARY KEY (ORDER_DETAILS_ID);

ALTER TABLE PIZZA_TYPES
ADD CONSTRAINT PIZZA_TYPES_PKEY PRIMARY KEY (PIZZA_TYPE_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT ORDERS_PKEY PRIMARY KEY (ORDER_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (CUSTID) REFERENCES CUSTOMERS (CUSTID);

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

ALTER TABLE ORDER_DETAILS
ADD CONSTRAINT FK_CHILD_PARENT_PRODUCT FOREIGN KEY (PIZZA_ID) REFERENCES PIZZAS (PIZZA_ID);

ALTER TABLE PIZZAS
ADD CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PIZZA_TYPE_ID) REFERENCES PIZZA_TYPES (PIZZA_TYPE_ID);


--Data Analysis

--1.1 Total unique orders
SELECT
	COUNT(DISTINCT ORDER_ID)
FROM
	ORDERS;

--1.2 Orders by month
WITH
	MONTHLY_ORDERS AS (
		SELECT
			DATE_TRUNC('month', ORDER_DATE) AS MONTH,
			COUNT(ORDER_ID) AS ORDER_COUNT
		FROM
			ORDERS
		GROUP BY
			DATE_TRUNC('month', ORDER_DATE)
	)
SELECT
	MONTH,
	ORDER_COUNT,
	LAG(ORDER_COUNT) OVER (
		ORDER BY
			MONTH
	) AS PREV_MONTH,
	ROUND(
		100.0 * (
			ORDER_COUNT - LAG(ORDER_COUNT) OVER (
				ORDER BY
					MONTH
			)
		) / NULLIF(
			LAG(ORDER_COUNT) OVER (
				ORDER BY
					MONTH
			),
			0
		),
		2
	) MOM_GROWTH_PCT
FROM
	MONTHLY_ORDERS
ORDER BY
	MONTH;

--1.3 Orders by day of week 
SELECT
	TO_CHAR(ORDER_DATE, 'Day') AS WEEKDAY,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM
	ORDERS
GROUP BY
	WEEKDAY
ORDER BY
	TOTAL_ORDERS DESC;

--1.4 Average orders per customer
SELECT
	ROUND(
		COUNT(DISTINCT ORDER_ID) * 1.0 / COUNT(DISTINCT CUSTID),
		2
	) AS AVG_ORDERS_PER_CUSTOMER
FROM
	ORDERS

--1.5 Repeat customers with frequency
SELECT
	CUSTID,
	COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
FROM
	ORDERS
GROUP BY
	CUSTID
ORDER BY
	ORDER_COUNT DESC;

--1.6 cumulative order trend- Growth trend based on historical data
--a. Monthly trends
WITH
	MONTHLY_ORDERS AS (
		SELECT
			DATE_TRUNC('month', ORDER_DATE) AS MONTH,
			COUNT(ORDER_ID) AS ORDER_COUNT
		FROM
			ORDERS
		GROUP BY
			DATE_TRUNC('month', ORDER_DATE)
	)
SELECT
	MONTH,
	ORDER_COUNT,
	LAG(ORDER_COUNT) OVER (
		ORDER BY
			MONTH
	) AS PREV_MONTH,
	ROUND(
		100.0 * (
			ORDER_COUNT - LAG(ORDER_COUNT) OVER (
				ORDER BY
					MONTH
			)
		) / NULLIF(
			LAG(ORDER_COUNT) OVER (
				ORDER BY
					MONTH
			),
			0
		),
		2
	) MOM_GROWTH_PCT
FROM
	MONTHLY_ORDERS
ORDER BY
	MONTH;

--b. Cumulative order trends
SELECT
	ORDER_DATE,
	COUNT(ORDER_ID) AS DAILY_ORDERS,
	SUM(COUNT(ORDER_ID)) OVER (
		ORDER BY
			ORDER_DATE
	) AS CUMULATIVE_ORDERS
FROM
	ORDERS
GROUP BY
	ORDER_DATE
ORDER BY
	ORDER_DATE

--2. Total revenue from pizza sales(price * quantity)
SELECT
	SUM(OD.QUANTITY * P.PRICE) AS TOTAL_REVENUE
FROM
	ORDER_DETAILS OD
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID;

--3. Hightest priced pizza
SELECT
	PT.NAME,
	P.SIZE,
	CONCAT('$', P.PRICE) AS PRICE
FROM
	PIZZAS P
	JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
ORDER BY
	P.PRICE DESC;

--4. most common pizza size orderd
SELECT
	P.SIZE,
	COUNT(*) AS TOTAL_ORDERS
FROM
	ORDER_DETAILS OD
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES PT ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID
GROUP BY
	P.SIZE
ORDER BY
	TOTAL_ORDERS DESC
LIMIT
	1;

--5. Top 5 most ordersd pizza types
SELECT
	P.PIZZA_ID,
	SUM(OD.QUANTITY) AS TOTAL_QTY
FROM
	ORDER_DETAILS OD
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	P.PIZZA_ID
ORDER BY
	TOTAL_QTY DESC
LIMIT
	5;

--6. Total quantity by pizza category
SELECT
	PT.CATEGORY,
	SUM(OD.QUANTITY) AS TOTAL_QTY
FROM
	ORDER_DETAILS OD
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	PT.CATEGORY

--7. Order by Hour of the day
SELECT
	TO_CHAR(ORDER_TIME::TIME, 'HH24:00') AS ORDER_HOUR,
	COUNT(*) AS ORDER_COUNT
FROM
	ORDERS
GROUP BY
	ORDER_HOUR
ORDER BY
	ORDER_HOUR;

--8. Average pizza ordered per day
SELECT
	ROUND(AVG(DAILY_TOTAL), 0) AS AVG_PIZZA_PER_DAY
FROM
	(
		SELECT
			O.ORDER_DATE,
			SUM(OD.QUANTITY) AS DAILY_TOTAL
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			ORDER_DATE
	) T;

--9. Top 3 pizzas by revenue
WITH
	PIZZA_REVENUE AS (
		SELECT
			PT.NAME,
			SUM(OD.QUANTITY * P.PRICE) AS REVENUE,
			RANK() OVER (
				ORDER BY
					SUM(OD.QUANTITY * P.PRICE) DESC
			) AS RANK
		FROM
			ORDER_DETAILS OD
			JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
			JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
		GROUP BY
			PT.NAME
	)
SELECT
	NAME,
	REVENUE
FROM
	PIZZA_REVENUE
WHERE
	RANK <= 3;

--Advanced Analysis
--10. Revenue contribution per pizza
SELECT
	PT.NAME,
	SUM(OD.QUANTITY * P.PRICE) AS REVENUE,
	CONCAT(
		ROUND(
			100 * SUM(OD.QUANTITY * P.PRICE) / SUM(SUM(OD.QUANTITY * P.PRICE)) OVER (),
			2
		),
		'%'
	) AS PER_CONTRIBUTION
FROM
	ORDER_DETAILS OD
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	PT.NAME
ORDER BY
	PER_CONTRIBUTION DESC;

--11. Cumulative order revenue over time
SELECT
	ORDER_DATE,
	DAILY_REVENUE,
	SUM(DAILY_REVENUE) OVER (
		ORDER BY
			ORDER_DATE
	) AS CUMULATIVE_REVENUE
FROM
	(
		SELECT
			O.ORDER_DATE,
			SUM(OD.QUANTITY * P.PRICE) AS DAILY_REVENUE
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
			JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
		GROUP BY
			O.ORDER_DATE
	) T;

--12. Top 3 pizzas by category (revenue based)
WITH
	CAT_RANK AS (
		SELECT
			PT.CATEGORY,
			PT.NAME,
			SUM(OD.QUANTITY * P.PRICE) AS REVENUE,
			RANK() OVER (
				PARTITION BY
					PT.CATEGORY
				ORDER BY
					SUM(OD.QUANTITY * P.PRICE) DESC
			) AS RANK
		FROM
			ORDER_DETAILS OD
			JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
			JOIN PIZZA_TYPES PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
		GROUP BY
			PT.CATEGORY,
			PT.NAME
	)
SELECT
	CATEGORY,
	NAME,
	REVENUE
FROM
	CAT_RANK
WHERE
	RANK <= 3;


--Extended business case studies
--13. Top 10 customers by spending
SELECT
	C.CUSTID,
	C.FIRST_NAME || ' ' || C.LAST_NAME AS NAME,
	SUM(OD.QUANTITY * P.PRICE) AS TOTAL_SPENT
FROM
	CUSTOMERS C
	JOIN ORDERS O ON C.CUSTID = O.CUSTID
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
	JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
GROUP BY
	C.CUSTID,
	NAME
ORDER BY
	TOTAL_SPENT DESC
LIMIT
	10;

--14. Average order size
SELECT
	ROUND(AVG(ORDER_SIZE), 0) AS AVG_ORDER_SIZE
FROM
	(
		SELECT
			OD.ORDER_ID,
			SUM(OD.QUANTITY) AS ORDER_SIZE
		FROM
			ORDER_DETAILS OD
		GROUP BY
			OD.ORDER_ID
	) T;

--15. Seasonal Trends
SELECT
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	) AS MONTH,
	COUNT(*) AS TOTAL_ORDERS
FROM
	ORDERS
GROUP BY
	EXTRACT(
		MONTH
		FROM
			ORDER_DATE
	) ORDER BY MONTH;

--16. Customer Segmentation
WITH
	CUST_SPENT AS (
		SELECT
			C.CUSTID,
			SUM(OD.QUANTITY * P.PRICE) AS TOTAL_SPENT
		FROM
			CUSTOMERS C
			JOIN ORDERS O ON C.CUSTID = O.CUSTID
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
			JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
		GROUP BY
			C.CUSTID
	)
SELECT
	CASE
		WHEN TOTAL_SPENT > 100500 THEN 'High Value'
		ELSE 'Regular'
	END AS SEGMENT,
	COUNT(*) AS CUSTOMER_COUNT
FROM
	CUST_SPENT
GROUP BY
	SEGMENT;

--17. Repeat customer rate
WITH
	CUST_ORDERS AS (
		SELECT
			CUSTID,
			COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT
		FROM
			ORDERS
		GROUP BY
			CUSTID
	)
SELECT
	ROUND(
		100.0 * SUM(
			CASE
				WHEN ORDER_COUNT > 1 THEN 1
				ELSE 0
			END
		) / COUNT(*),
		2
	) AS REPEAT_RATE
FROM
	CUST_ORDERS;



















